# Generated by Django 3.1.7 on 2021-06-24 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='transaction',
            new_name='transaction_id',
        ),
    ]
